# Generated by Django 5.0.4 on 2024-04-21 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_project', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='performer_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer_project', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='performer_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer_task', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
