# Generated by Django 5.0.4 on 2024-04-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_author_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status_project',
        ),
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(blank=True, default='Создано', max_length=20, null=True, verbose_name='Стаутс'),
        ),
    ]
