# Generated by Django 5.0.4 on 2024-04-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_status_project_alter_task_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(blank=True, default='создано', max_length=20, null=True, verbose_name='Стаутс'),
        ),
    ]
