# Generated by Django 5.0.4 on 2024-04-23 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_task_status_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='project.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(default='создано', max_length=20, verbose_name='Стаутс'),
        ),
    ]
