# Generated by Django 5.0.4 on 2024-04-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_task_project_task_alter_task_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_project',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_task',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
